apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  namespace: his-kafka
  labels:
    app: kafka-producer
spec:
  type: NodePort
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30801
      name: http
