apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
  namespace: his-kafka
  labels:
    app: kafka-consumer
spec:
  type: NodePort
  selector:
    app: kafka-consumer
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30802
      name: http
