apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: k3s-kafka
data:
  server.properties: |
    process.roles=broker,controller
    node.id=1
    controller.quorum.voters=1@k3s-kafka-0.k3s-kafka-headless.k3s-kafka.svc.cluster.local:9093
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
    advertised.listeners=PLAINTEXT://k3s-kafka-0.k3s-kafka-headless.k3s-kafka.svc.cluster.local:9092,EXTERNAL://NODE_IP:30092
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT
    cluster.id=k3s-kafka-cluster-id
    log.dirs=/var/lib/kafka/data
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    default.replication.factor=1
    min.insync.replicas=1
    num.partitions=1
    auto.create.topics.enable=false
    compression.type=gzip
    log.retention.hours=168
    log.retention.bytes=1073741824
    log.segment.bytes=536870912
